In [1]:
import numpy as np
jk = np.array([1,2,3,4,6])
print(jk.itemsize)

4


In [2]:
import numpy as np
smp = [5,6,7]
lk = np.asarray(smp)
print(lk)

[5 6 7]


In [4]:
import numpy as np
a = np.arange(10)
s = slice(3,9,3)
lp = a[s]
print(lp)

[3 6]


In [5]:
import numpy as np
kl = np.arange(10)
l = kl[2:7:2]
print(l)

[2 4 6]


In [6]:
import numpy as np
kl = np.arange(0,60,5)
kl = kl.reshape(3,4)
for x in np.nditer(kl):
    print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [7]:
import numpy as np
arr1 = np.array([1.2,3.567,4.5,7.89])
print(np.around(arr1))

[1. 4. 4. 8.]
